# Sample workflow for building and deploying a Gatsby site to GitHub Pages
#
# To get started with Gatsby see: https://www.gatsbyjs.com/docs/quick-start/
#
name: Deploy to Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.18"
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            docs/node_modules
          key: ${{ runner.os }}-web-build-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies web/docs
        run: npm ci
        working-directory: web/docs
      - name: Install dependencies web
        run: npm ci
      - name: Build web/docs
        run: npm run build
        working-directory: web/docs
      - name: Build app
        run: npm run test && npm run build
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: counters
          directory: web/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
